name: Test Automation

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------
      # Python Setup
      # -------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # -------------------------
      # Install Node + Appium
      # -------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2

      # -------------------------
      # Install Android SDK + Emulator
      # -------------------------
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Emulator Packages
        run: |
          sdkmanager "platform-tools" "emulator" "system-images;android-30;google_apis;x86_64"

      - name: Create Emulator
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64"

      - name: Start Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82

      # -------------------------
      # Start Appium Server
      # -------------------------
      - name: Start Appium
        run: |
          appium &
          sleep 10

      # -------------------------
      # Run Tests (API + WEB + MOBILE)
      # -------------------------
      - name: Run Tests
        run: |
          pytest tests --alluredir=allure-results

      # -------------------------
      # Upload Allure Report
      # -------------------------
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
