name: Automation (API + Web + Mobile)

on:
  push:

jobs:

  # ================= API =================
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run API Tests
        run: pytest tests/api --alluredir=allure-results-api


  # ================= WEB =================
  web-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright
        run: playwright install --with-deps

      - name: Run Web Tests
        run: pytest tests/web --alluredir=allure-results-web


  # ================= MOBILE =================
  mobile-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          npm install -g appium

      - name: Run Emulator & Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel

          emulator-options: >-
            -no-window
            -no-audio
            -no-boot-anim
            -gpu swiftshader_indirect
            -accel off
            -no-snapshot

          script: |
            echo "Waiting for emulator..."
            adb wait-for-device

            echo "Installing APK..."
            adb install app.apk || true

            echo "Starting Appium..."
            appium > appium.log 2>&1 &

            sleep 20

            echo "Running Mobile Tests..."
            pytest tests/mobile --alluredir=allure-results-mobile
